### ISSUE TITLE
Bind doesn't work for complex types like data.frame

### ISSUE THREAD

**Issue by scottstanfield** [mailund/bindr#2]
Would love to use bind to unpack arguments that are complex, like a data.frame. Reproducible example:

```
bind(a, b) %<-% c(1, 2)
class(a) == "numeric"
class(b) == "numeric"

# mtcars is R sample data.frame of car data
bind(a, b) %<-% c("hello", mtcars)
class(a) == "character"
class(b) == class(mtcars)   # <-- fails

# b takes the result of the first entry of mtcars: mtcars[1,1]
b == mtcars[1,1]   # TRUE
```

**Comment by mailund** [comment]
Will take a look at that. I don't see why this doesn't work already, but I will have a look

**Comment by scottstanfield** [comment]
Thanks. I'm looking too. Something in .unpack. The difference between [[ ]] and [ ]...

**Comment by scottstanfield** [comment]
There might be something to to `list2env`:

```
value <- c(a="hello", b=mtcars))
list2env(value, .GlobalEnv)

# now a is a character string and b is a data.table
# this isn't exactly what bind is trying to do, but it's interesting

**Comment by scottstanfield** [comment]
Might have a fix, but without some testing, not sure if this is the right approach. Replacing the line at: https://github.com/mailund/bindr/blob/master/R/bind.R#L74

`val <- .unpack(value[i])`

with

`val <- value[[i]]`

gives me the result I was looking for.

**Comment by scottstanfield** [comment]
I'm close. Using the one line above, I can pass the `list` test, but not the `c` test:

```
  bind(a, b) %<-% list('hello', mtcars)
  expect_equal(a, 'hello')
  expect_equal(b, mtcars)       # <-- passes
  rm(a) ; rm(b)

  bind(a, b) %<-% c('hello', mtcars)
  expect_equal(a, 'hello')
  expect_equal(b, mtcars)       # <-- fails
  rm(a) ; rm(b)
```

**Comment by scottstanfield** [comment]
I think the above behavior is working as expected. Using `c(mtcars)` will decompose the data.table into a sequence of vectors. So in the case of `bind(a, b) %<-% c('hello', mtcars)` above, `b` becomes the first vector `mpg` from the mtcars sample dataset. 

So if one was using bind() to unpack a complex "tuple", then it should be coming from a list, not a vector. 

I'm try a few more complex objects.

**Comment by scottstanfield** [comment]
Sent a PR. Might work for you. 

https://github.com/mailund/bindr/pull/3

**Comment by mailund** [comment]
Thanks, I've merged the PR.

**Comment by scottstanfield** [comment]
Awesome. I’m already using it in production now. Thanks for the work!
